<<<<<<< HEAD
/* -*- mode: c; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; c-file-style: "stroustrup"; -*- 
 *
 * This file is part of Gromacs        Copyright (c) 1991-2004
 * David van der Spoel, Erik Lindahl, University of Groningen.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * To help us fund GROMACS development, we humbly ask that you cite
 * the research papers on the package. Check out http://www.gromacs.org
 * 
 * And Hey:
 * Gnomes, ROck Monsters And Chili Sauce
 */
#ifndef _NB_KERNEL_SSE2_DOUBLE_H_
#define _NB_KERNEL_SSE2_DOUBLE_H_

/*! \file  nb_kernel_sse2_double.h
 *  \brief SSE2-intrinsics optimized level2 nonbonded kernels.
 *
 *  \internal
 */

#include <stdio.h>

#include <types/simple.h>

#include "../nb_kerneltype.h"

#ifdef __cplusplus
extern "C" {
#endif
#if 0
}
#endif


void
nb_kernel_setup_sse2_double(FILE *log,nb_kernel_t **list);

#ifdef __cplusplus
}
#endif

#endif /* _NB_KERNEL_SSE2_DOUBLE_H_ */
=======
/*
 * Note: this file was generated by the Gromacs c kernel generator.
 *
 *                This source code is part of
 *
 *                 G   R   O   M   A   C   S
 *
 * Copyright (c) 2001-2012, The GROMACS Development Team
 *
 * Gromacs is a library for molecular simulation and trajectory analysis,
 * written by Erik Lindahl, David van der Spoel, Berk Hess, and others - for
 * a full list of developers and information, check out http://www.gromacs.org
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * To help fund GROMACS development, we humbly ask that you cite
 * the papers people have written on it - you can find them on the website.
 */
#ifndef nb_kernel_sse2_double_h
#define nb_kernel_sse2_double_h

#include "../nb_kernel.h"


/* List of kernels for this architecture with metadata about them */
extern nb_kernel_info_t
    kernellist_sse2_double[];

/* Length of kernellist_c */
extern int
    kernellist_sse2_double_size;

#endif
>>>>>>> 2aa1ce7f6f65a45829ff249723a2667c864a68b2
